### ISSUE TITLE
[website] Potentially remove the ability to drag ASes around

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#104]
I don’t see how this adds to the functionality, and you can drag the entire graph off screen, or drag an AS out of viewwhich I don’t think is helpful. It’s not like you can drag ASes anywhere, it looks like peers only go left to right and every AS must stay on the same level. There’s also no button to reset it to it’s original state. Maybe there is a use case here that I am not seeing, but I’m struggling a bit to see why this is here

**Comment by Arvonit** [comment]
I believe we discussed not doing this during the meeting. It's nice to have some sort of interactivity with the graph, especially if you want to move one node further away from another

**Comment by jfuruness** [comment]
I don't recall this discussion and I'm struggling to see the benefit of this feature since you can only moved nodes to the left or right. Either way, We need to keep this for now due to the vis-network displaying graphs incorrectly
