### ISSUE TITLE
[Website] ROA state

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#123]
If I edit the default example’s announcement from the attacker to have a /16 prefix an a 777 origin, the ROA state is still invalid when it should be valid

**Comment by Arvonit** [comment]
Should be fixed now

<img width="490" alt="image" src="https://github.com/jfuruness/bgpy_pkg/assets/27634841/ab9fe8c6-8305-461d-a2e7-5f2fd0bdac21">
