### ISSUE TITLE
[website] Fields can be left blank when creating a roa and buttons will just silently fail

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#128]

**Comment by Arvonit** [comment]
Fixed. ROAs now also give error toasts if fields aren't valid

**Comment by jfuruness** [comment]
Same comment I made on another ticket - is there a reason we don't just add a little red subtext that says the field is required (which seems to me to be common practice)? It feels weird to me to have a pop up in a different place, especially when if you leave all fields blank only one pop up shows up. Additionally, if you click add multiple times, you're going to get multiple pop ups for the same things.
