### ISSUE TITLE
[website] Use syntax for AS path of 666-1-2 instead of 666, 1, 2

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#132]
I guess dashes are more common than commas for AS-Path syntax

**Comment by Arvonit** [comment]
Website now supports both syntaxes

**Comment by jfuruness** [comment]
I think Amir wanted to display the AS path that way always if my
understanding is correct. Dr. Wang also pointed out that using dashes is
the more common syntax for the AS-Path which I didn't realize.

Thanks,
Justin
