### ISSUE TITLE
[website] Hexagons have extremely variable sizes compared to the typical picture diagrams (probably will be fixed by moving to a graphviz library)

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#135]

**Comment by Arvonit** [comment]
I made the nodes to much be closer in size now. Before, it calculated the size of each node just based on the length of its local RIB, now it ensures each node is at least 75% of the size of the largest node

**Comment by jfuruness** [comment]
for the ASPA example AS 5 is way smaller than the rest, so I’m not sure that ASes are actually 75% of the size. It definitely looks much better though, although I think it would probably look much nicer if the nodes where sized the same way as the graphviz lib does it

**Comment by jfuruness** [comment]
ASPA example now also does not display correctly with the overlapping lines
