### ISSUE TITLE
[website] Capturing scroll in the graph should be removed

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#46]
As discussed in the meeting, the graph can unexpectedly capture the scroll from your mouse. This is also exasperated due to the lack of border around the graph. Without much pros for this feature, this should be removed, and potentially allow for zooming with some sort of button on the graph (although perhaps once we resize the graph this may not be necessary)

**Comment by jfuruness** [comment]
If you simulate, then clear the graph, then try to scroll down, it looks like the page is just broken, but really the empty graph is capturing the scroll (imo this scroll capture should be disabled)

**Comment by jfuruness** [comment]
Use the subprefix hijack with custom announcements workflow. Click on node 777 to modify it. Scroll down… you can’t, it’s captured

**Comment by Arvonit** [comment]
You can use cmd/ctrl + scroll or use buttons above the graph to zoom

**Comment by jfuruness** [comment]
If you've added cmd/ctrl + scroll as a feature can you document it where it says "zoom in" "zoom out" when hovering over the buttons? Otherwise I don't think users will know that this feature exists
