### ISSUE TITLE
[website] enlarge js graph

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#68]
The window that the graph is displayed in is much smaller than the space that it could take up on the screen.

**Comment by Arvonit** [comment]
Graph defaults to 2/3 of the screen now, but can be adjusted with the sidebar resizer

**Comment by jfuruness** [comment]
I still think there's a bunch of whitespace here that could be taken up by the graph. The icons on the top right have a whole row devoted to them, they could be moved somewhere else. The diagram dropdown also has a whole row devoted to it, and I think that could just be on the left side. The left side also has a lot of whitespace in all the text boxes. Our goal is to make the interactive graphs as clear as the PNGs. If you take for example the subprefix hijack example, and simulate it, the PNG is way more clear than the diagram even though the diagram could fit where the interactive graph is for the most part. Additionally, the sidebar doesn't move much from side to side.
