### ISSUE TITLE
[website] ASPA graph resizing

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#71]
Click on example, subprefix hijack. Then click on example, ASPA. ASPA graph is outside of the screen. If you load the page up, and originally click on the ASPA graph, the graph is inside the screen.

**Comment by jfuruness** [comment]
If I click on subprefix hijack, simulate, then switch to the ASPA example, and simulate, the same thing happens. What is causing the sizing of the graph to change based on previous state?

**Comment by Arvonit** [comment]
This is what it looks like for me when I do it. I use vis-network's fit function every time a simulation is ran or config is loaded, so it should fit on the screen. Does it look different on your end?

<img width="1512" alt="image" src="https://github.com/jfuruness/bgpy_pkg/assets/27634841/513073e9-3f48-45c9-b6d4-1c7c74b50b00">

**Comment by jfuruness** [comment]
I think we synced up on this and discussed potentially adding a buffer

**Comment by Arvonit** [comment]
I added a bit of a margin when centering the graph. It's not perfect, but it's good enough for most cases
