### ISSUE TITLE
[website]  Error messages move all HTML on the screen

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#73]
Error messages, in a very jarring motion, push all content down the screen on and off if you click simulate twice for instance. Prob would be nicer to have just next to the title or something so that the entire page isn’t moving like that

**Comment by Arvonit** [comment]
I changed the error message from showing up as a banner to a toast

**Comment by jfuruness** [comment]
Can you change the CSS to make this be some color other than white? White tends to blend in with the background quite a bit. Maybe red or yellow?

**Comment by Arvonit** [comment]
Strangely, the background is red when running locally, but white when I deploy to the server. Will need to investigate more
<img width="381" alt="image" src="https://github.com/jfuruness/bgpy_pkg/assets/27634841/be2cff7c-48ac-4f8f-b4cc-cceb5e2c712c">
