### ISSUE TITLE
[website] graph resizing doesn't happen after sim

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#76]
Default ASPA simulations go out of the screen

**Comment by jfuruness** [comment]
Still happens, what causes the graphs to resize like this?

**Comment by Arvonit** [comment]
I think we should discuss this more over Slack bc I'm a bit confused what resizing is happening. It seems fine on my end

**Comment by jfuruness** [comment]
discussed if I remember correctly
