### ISSUE TITLE
[website] line intersection algo?

### ISSUE THREAD

**Issue by jfuruness** [jfuruness/bgpy_pkg#89]
If you take the subprefix hijack example, and add a customer to AS 1, it intersects with other lines for no reason

**Comment by Arvonit** [comment]
It doesn't seem like there's a way to avoid this. The vis-network library handles drawing the lines without a way to override it

**Comment by jfuruness** [comment]
This is an unfortunate problem. On some examples, such as https://bgpy.engr.uconn.edu/#bgp-prop this behavior makes the graph incorrect. Are there other modules that can fix this? I don't think this is something that can really be avoided
